### ISSUE TITLE
`empty` sugar unimplemented

### ISSUE THREAD

**Issue by seizethedave** [CozySynthesizer/cozy#15]
See here:
https://github.com/CozySynthesizer/cozy/blob/851dd0e6f003275b2690f7ad4e848a9c7c335dbf/cozy/codegen/cxx.py#L539

**Comment by seizethedave** [comment]
(Definitely the kind of low-hanging fruit that would make a good "me" task.)

**Comment by Calvin-L** [comment]
Ack, sorry if you were actively working on this. I committed a fix since I was running into the same issue and didn't notice you'd self-assigned this. :(

**Comment by seizethedave** [comment]
Not a prob. I hadn't started yet.
