### ISSUE TITLE
Incorrect code generated in guarded statement

### ISSUE THREAD

**Issue by seizethedave** [CozySynthesizer/cozy#17]
Minimal spec showing the issue: (boundsbug.ds)

```
BoundsBug:
    type Token = {
        score : Int
    }

    state tokens : Set<(Int, Token)>
    state total : Int

    invariant unique [s.0 | s <- tokens];
    invariant unique [s | s <- tokens];
    invariant len tokens < 5;

    op addToken(score : Int)
        assume not ((len tokens) in [s.0 | s <- tokens]);

        if (len tokens < 5) {
            total = total + score;
            tokens.add((len tokens, { score: score }));
        }

    query getTotalScore()
        total

    query getSummedScore()
        sum [tok.1.score | tok <- tokens]

    query getNumTokens()
        len tokens
```

A Java driver program:
```
public class Foo {
  public static void main(String[] args) {
    BoundsBug b = new BoundsBug();

    for (int i = 1; i < 7; i++) {
      b.addToken(i);
      System.out.println(String.format(
       "added token %d. now there are %d tokens and the total is %d but by summing the total is %d.",
       i, b.getNumTokens(), b.getTotalScore(), b.getSummedScore()));
    }
  }
}
```

Running this command:

`cozy --simple --java=BoundsBug.java boundsbug.ds && javac *.java && java Foo`

...yields the results:

> added token 1. now there are 1 tokens and the total is 1 but by summing the total is 1.
> added token 2. now there are 2 tokens and the total is 3 but by summing the total is 3.
> added token 3. now there are 3 tokens and the total is 6 but by summing the total is 6.
> added token 4. now there are 4 tokens and the total is 10 but by summing the total is 10.
> added token 5. now there are 5 tokens and the total is 10 but by summing the total is 15.
> added token 6. now there are 5 tokens and the total is 10 but by summing the total is 15.

When we process the 5th token, the `Set` gets the final token added but the `total` field does not. This is because the generated (`--simple`) Java code has this structure:

```
addToken(score):
   v60 = all tokens from this.tokens
   if count(this.tokens) < 5:
      remove all from v60 that match entries in this.tokens
      v60.remove(count(this.tokens), new token(...))
   else:
      remove all tokens from v60

   remove from this.tokens any tokens left in v60.

   v74 = empty list of tokens
   if (count(this.tokens) < 5):
      load all from this.tokens into v74
      v74.add(count(tokens), new token(...))
   else:
      load all from this.tokens into v74

   remove from v74 any tokens that exist in this.tokens.
   add to this.tokens any tokens left in v74.

   if count(this.tokens) < 5:
      total = total + score
```

That is, the guard condition is recomputed between adding a token and adding to the `total` instance variable.

**Comment by Calvin-L** [comment]
Good diagnosis.

During codegen we sometimes desugar complicated constructs into simpler ones. See the implementation of [in](https://github.com/CozySynthesizer/cozy/blob/8b65d7fbba5ecfd476245b29090b6793b4b703f5/cozy/codegen/cxx.py#L393) for instance. I suspect that the problem is that somewhere we duplicate the "compute-sum" expression and re-use it both before and after the update takes place.

**Comment by seizethedave** [comment]
Way shorter spec showing the issue:

```
BoundsBug2:
    state executions : Int
    state bugHappened : Bool

    op exec()
        executions = 1;

        if (executions == 0) {
            bugHappened = true;
        }

    query didBugHappen()
       bugHappened
```

The problem is reading a variable after modifying it.
