### ISSUE TITLE
rethink `with_type`

### ISSUE THREAD

**Issue by izgzhen** [CozySynthesizer/cozy#87]
This is a very error-prone feature to have.

I propose two patches to add, either:

- add a guard in `with_type`, which checks if the underlying expression is compatible with the to-be-set type at all (deterministic type checking)
- somehow make our language capable of inferencing type itself. we shouldn't need to set them manually in between the pipeline

**Comment by Calvin-L** [comment]
Type inference is possible if all the variables in an expression are correctly annotated. The `retypecheck` function in `typecheck.py` provides this functionality.
