### ISSUE TITLE
Implement an improvement iteration number based timeout mechanism

### ISSUE THREAD

**Issue by izgzhen** [CozySynthesizer/cozy#96]
@anhnamtran Do you want to add this yourself?

**Comment by izgzhen** [comment]
Hopefully we can archive some degree of determinism even we run synthesis on different type of machines

**Comment by anhnamtran** [comment]
Do you mean putting a cap on the number of improvements done instead of just having a time out?

**Comment by izgzhen** [comment]
> Do you mean putting a cap on the number of improvements done instead of just having a time out? If so, where would a counter like this go? Would it be somewhat similar to what was added in #93?

This feature will be based on the counter you added. We can compare the counter with the cap to decide whether to stop the iteration.

> Also would this replace the timeout or are we implementing it in a "first to finish" way?

We should have both of them. We will measure two metrics in future to describe the _speed_ of synthesis: 

1. Time spent under fixed improvement iteration number
2. Improvement iterations under fixed time

**Comment by anhnamtran** [comment]
> This feature will be based on the counter you added. We can compare the counter with the cap to decide whether to stop the iteration.

In which case, what would be a reasonable "default" to this? I don't believe we should have a default, considering the number of iterations Cozy goes through can be different for different specs.

**Comment by izgzhen** [comment]
> In which case, what would be a reasonable "default" to this? I don't believe we should have a default, considering the number of iterations Cozy goes through can be different for different specs.

Yeah, just switch it off by default. Maybe `None`.

**Comment by Calvin-L** [comment]
Pull request #99 added the `--improvement-limit` parameter, which I believe resolves this ticket.
